### PR TITLE
fix invalid cmd

### PR DESCRIPTION
**Pull request by songleo**
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by songleo** [comment]
when this PR is merged, we will cherry-pick it into the 2.4 release. @dockerymick FYI

**Review by morvencao — APPROVED** [review]
/lgtm

thanks

**Review by dockerymick — APPROVED** [review]
This looks good, moving forward, please create a portal doc issue to track the updates

**Comment by dockerymick** [comment]
Merging this PR

**Comment by songleo** [comment]
portal doc issue: https://github.com/open-cluster-management/backlog/issues/17654

**Pull request merged**
