### PR TITLE
added placement strategy

### PR DESCRIPTION
**Pull request by jc-berger**
See Jira: https://issues.redhat.com/browse/ACM-6806

### CODE REVIEW

**Review by swopebe — APPROVED** [review]
This looks really good, I even have a good understanding about why the user would want to use it. One small thing:

Then, it divides the clusters not included...

We usually are very specific: Then, it divides the clusters _that are_ not included

(for clarity)

**Comment by haoqing0110** [comment]
@jc-berger @swopebe there's some concern in https://issues.redhat.com/browse/ACM-5651 (see the last comments), plz help to hold this PR.

**Comment by jc-berger** [comment]
@haoqing0110 thanks for directing our attention. hanks for directing our attention. Yes, I'll hold off on merging this PR

Let me know if any more work needs to be done for this PR regarding the decision strategy. Otherwise, I'll stand by.

**Comment by dockerymick** [comment]
@jc-berger for your work on this. @swopebe thanks for providing your review and approval. @haoqing0110 I echo Jake's thanks. @jc-berger let's close this PR since it is for 2.10. I will add the link for your PR onto the issue.

**Pull request closed without merging**
