### PR TITLE
stolostron/backlog#20089 firmware host

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Review by achuzhoy — COMMENTED** [review]
/lgtm
nit: I'd personally use a different wording, because we have 2 sentences beginning with the same "If you do not have" wording. But the message is right.

**Comment by cadawson** [comment]
@achuzhoy Thanks for the quick review. I changed the wording a bit. This is only 2.5, correct?

**Comment by achuzhoy** [comment]
> @achuzhoy Thanks for the quick review. I changed the wording a bit. This is only 2.5, correct?

Looks good!
Thanks.

**Comment by achuzhoy** [comment]
I saw it in 2.4

**Comment by cadawson** [comment]
Made change to 2.4, as well.

**Pull request merged**
