### PR TITLE
acm2394 upd icsp disco 2.6

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
Hi @chadcrum. Does this section for the ICSP cover this issue? I updated the file reference. Thanks!

**Comment by chadcrum** [comment]
Hi @cadawson - [This section](https://github.com/stolostron/rhacm-docs/blob/2c94a3da8dcc47a35d86dec3ecc741cbe307925e/clusters/cluster_lifecycle/create_infra_env.adoc) should be updated as well:

```
    [[registry]]
       prefix = ""
       location = "quay.io/edge-infrastructure"
       mirror-by-digest-only = false

       [[registry.mirror]]
       location = "mirror1.registry.corp.com:5000/edge-infrastructure"
```
should be changed to
```
    [[registry]]
       prefix = ""
       location = "registry.redhat.io/multicluster-engine"
       mirror-by-digest-only = true

       [[registry.mirror]]
       location = "mirror.registry.com:5000/multicluster-engine"
```

**Comment by cadawson** [comment]
Thanks @chadcrum . I updated the example "ConfigMap." I will port it to 2.7. Let me know if it looks ok, or if something needs to change. Thanks!

**Review by chadcrum — APPROVED** [review]

**Review by oafischer — APPROVED** [review]
lgtm

**Pull request merged**
