### PR TITLE
ACM#9085: Add a link to the "Scaling down data plane to zero" section     

### PR DESCRIPTION
**Pull request by xenolinux**
https://issues.redhat.com/browse/ACM-9085

### CODE REVIEW

**Review by CrystalChun — APPROVED** [review]
/lgtm

**Review by davidvossel — COMMENTED** [review]
kubevirt part looks good

**Comment by CrystalChun** [comment]
Agent looks good (both baremetal and non baremetal)

**Comment by mkumatag** [comment]
cc @dharaneeshvrd

**Comment by dharaneeshvrd** [comment]
IBM Power changes look good.

**Review by dharaneeshvrd — APPROVED** [review]

**Review by swopebe — APPROVED** [review]
This looks great @xenolinux -- the only thing I want to ask is can we make 4.14.0 >
`4.x.0` with a line before saying:

replace x with current version??

The reason why is next release I have to ask if I can bump this up -- and so to eliminate the questioning in examples, I ask if we can use a variable. Sometimes we cannot...if this only applies to 4.14, then that makes sense, (and it might).

**Comment by xenolinux** [comment]
> This looks great @xenolinux -- the only thing I want to ask is can we make 4.14.0 > `4.x.0` with a line before saying:
> 
> replace x with current version??
> 
> The reason why is next release I have to ask if I can bump this up -- and so to eliminate the questioning in examples, I ask if we can use a variable. Sometimes we cannot...if this only applies to 4.14, then that makes sense, (and it might).

To-do: Open a follow up PR to change 4.14.0 instances.

**Comment by xenolinux** [comment]
> This looks great @xenolinux -- the only thing I want to ask is can we make 4.14.0 > `4.x.0` with a line before saying:
> 
> replace x with current version??
> 
> The reason why is next release I have to ask if I can bump this up -- and so to eliminate the questioning in examples, I ask if we can use a variable. Sometimes we cannot...if this only applies to 4.14, then that makes sense, (and it might).

https://github.com/stolostron/rhacm-docs/pull/6357/files

**Pull request merged**
