### PR TITLE
open-cluster-management/backlog#4907 starting architecture review

### PR DESCRIPTION
**Pull request by swopebe**
@jnpacker I am looking at this and it seems not too out of date for 2.1, but maybe missing a few things. 

In the About: Architecture section, should we talk about observability (we will have it in What's new)

and in the image, should we change "endpoint" to "Klusterlet" -- what else am I missing at a higher level?

### CODE REVIEW

**Comment by jnpacker** [comment]
@bcpswope Yes to both. Change endpoint to klusterlet and we should mention Observability

**Comment by swopebe** [comment]
Klusterlet in endpoint, Obs first in the OCP box, bottom of managed cluster-- reorder maybe.

Observability paragraph from Joydeep.

**Review by dockerymick — COMMENTED** [review]
I made a minor commit based on the live PR review i had earlier. I also added a conref. Changes look good to me!

**Review by dockerymick — APPROVED** [review]
I believe your last update is the image, going to approve

**Pull request merged**
