### PR TITLE
removing the important notice from policy tables

### PR DESCRIPTION
**Pull request by dockerymick**
https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/22430

### CODE REVIEW

**Review by drkho — COMMENTED** [review]
Hi, @dockerymick . In governance/policy_controllers.adoc, the configuration policy controller is the one to support "enforce" and "inform". However, the controller may not be able to enforce with some policies or policy templates.

Hi, @gparvin , please correct me if I am wrong here.

**Comment by gparvin** [comment]
The "important" note regarding remediation actions in the Policy Controllers section I think should be kept.  It would be nice if it was moved down to just after the list of Policy Controllers -- that may help it make more sense.

I agree that we don't need to state this limitation in the config samples.  So the following places (tables) should have the "important" note removed inside the tables detailing the fields:
- Memory usage policy table
- Namespace policy YAML table
- Image vulnerability policy YAML table
- Pod policy table
- Pod security policy table
- Role policy table
- Role binding policy table

I think that will improve the clarity, but @drkho feel free to look at his more -- I just did a quick look at where I thought this was confusing.
Thanks!

**Comment by dockerymick** [comment]
@drkho @gparvin thanks for both reviews and clarification. I have updated the files as suggested.

**Comment by dockerymick** [comment]
@drkho @gparvin thanks for both reviews and clarification. I have updated the files as suggested.

**Comment by dockerymick** [comment]
Moving forward with this merge

**Pull request merged**
