### PR TITLE
update cluster proxy addon

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/27039
https://github.com/stolostron/backlog/issues/27019

### CODE REVIEW

**Comment by swopebe** [comment]
This will have conflicts because I was working it also: https://github.com/stolostron/backlog/issues/26662

It seems there are doc issues that the doc team was not aware of. Asking @cadawson to look into this PR...I will close my issue.

**Comment by cadawson** [comment]
@xuezhaojun and @ldpliu I reviewed this PR. Please take a look at my changes and make sure that it still looks ok. Thank you!

**Comment by swopebe** [comment]
Please stop and see my note, I did this update in another issue. @cadawson please look at your git notices, thank you.

**Comment by xuezhaojun** [comment]
> Please stop and see my note, I did this update in another issue. @cadawson please look at your git notices, thank you.

Explain in https://github.com/stolostron/backlog/issues/27019#issuecomment-1358777660.

**Comment by xuezhaojun** [comment]
> @xuezhaojun and @ldpliu I reviewed this PR. Please take a look at my changes and make sure that it still looks ok. Thank you!

Thanks for the review @cadawson , it looks good to me after the rebase!

**Pull request merged**
