### PR TITLE
Update docs on enabling single node openshift feature

### PR DESCRIPTION
**Pull request by jamestalton**
Signed-off-by: James Talton <jtalton@redhat.com>

### CODE REVIEW

**Comment by cadawson** [comment]
Thanks @jamestalton . I made a couple of changes/additions to this:
1. I think it is planned to be Technology Preview in 2.4, rather than Dev Preview. 
2. Is this still going to be disabled, by default, even though it is Tech Preview? The way I am interpreting it is that there is no feature gate, but you still have to enable the feature.
3. I bumped the version of ACM to 2.4. Since 2.3 was dev preview, my guess is that we will need 2.4, or later. 
4. I bumped the OpenShift version up to 4.9, since this is 2.4. I left it as 4.8 for the release image, as I think you might be able to create a 4.8 cluster as a SNO cluster with 4.8. That is what we are using for the Dev Preview version on 2.3.
Let me know if I am off base on any of these. We can change them, as needed.

**Review by cadawson — CHANGES_REQUESTED** [review]
Looks good! Added a few comments to the PR.

**Comment by cadawson** [comment]
@jamestalton : I had some questions/comments. Can you take a look at the earlier comment? Thanks!

**Comment by jamestalton** [comment]
OCP 4.8+ for SNO support

I think there are two paths for SNO
- CIM/AI
- HIVE

I believe the SNO we are talking about here is the HIVE path through cluster create without CIM.
It is disable by default and must be enabled using the console configmap.

**Review by cadawson — APPROVED** [review]
Looks good. Thanks!

**Comment by cadawson** [comment]
Merging

**Pull request merged**
