### PR TITLE
[ACM-9811] Updated troubleshooting topic for MCH

### PR DESCRIPTION
**Pull request by dislbenn**
Related Jira Issue: [ACM-9811](https://issues.redhat.com/browse/ACM-9811)

### CODE REVIEW

**Comment by dislbenn** [comment]
@swopebe can we also back-port these changes into `release-2.9`?

**Review by oafischer — APPROVED** [review]
Looks great, thanks!

**Review by dockerymick — APPROVED** [review]
Thanks for the updates, this looks good to me!

**Pull request merged**
