### PR TITLE
Add missing `modules/`

### PR DESCRIPTION
**Pull request by dhaiducek**
Even though these are `modules/` folders missing in subdirectories, the symlink will point to the symlink in the parent directory and ultimately resolve to the modules directory at the repository root.

Also adds a `.asciidoctorconfig` for the VSCode AsciiDoc extension.
ref: https://github.com/asciidoctor/asciidoctor-vscode?tab=readme-ov-file#asciidoctor-config-file

The configuration takes the VSCode preview from this, with unrendered variables/attributes:
image
To this, with the attributes rendered:
image

ref: https://issues.redhat.com/browse/ACM-11678

### CODE REVIEW

**Comment by dhaiducek** [comment]
In addition to the missing `modules` symlinks, this is also the VSCode AsciiDoc config PR.

**Comment by dockerymick** [comment]
@dhaiducek this looks good to me, please create a doc issue for this work

**Review by dockerymick — APPROVED** [review]
Reminder to first add a doc issue for this PR

**Comment by dhaiducek** [comment]
> Reminder to first add a doc issue for this PR

Issue added: https://issues.redhat.com/browse/ACM-11678

**Comment by dockerymick** [comment]
@dhaiducek thanks Dale! Merging this PR then running a build for 2.11

**Pull request merged**
