### PR TITLE
BareMetal deprecation in 2.6

### PR DESCRIPTION
**Pull request by oafischer**
https://github.com/stolostron/backlog/issues/24461

### CODE REVIEW

**Comment by cadawson** [comment]
Hi @ldpliu . I think the console version of bare metal assets is being removed from 2.6. Can you confirm that this API is being deprecated and not removed? Thanks!

**Review by cadawson — CHANGES_REQUESTED** [review]
Looks good from a writing standpoint. I included a question to DangPeng to confirm if this is removed or deprecated. Aside from that, feel free to merge. Thanks!

**Comment by oafischer** [comment]
Thanks @cadawson, I'll wait for @ldpliu to chime in before merging.

**Comment by ldpliu** [comment]
> Hi @ldpliu . I think the console version of bare metal assets is being removed from 2.6. Can you confirm that this API is being deprecated and not removed? Thanks!

Yes, console has removed it from 2.6. But in backend, this api will be deprecate in 2.6, and removed in 2.7

**Comment by cadawson** [comment]
Thank you for the clarification @ldpliu !

**Review by cadawson — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
