### PR TITLE
stolostron/backlog#21091

### PR DESCRIPTION
**Pull request by swopebe**
--changing a note

### CODE REVIEW

**Review by cadawson — CHANGES_REQUESTED** [review]
By default, the auto-import secret is used one time and deleted when the import process completes. If you want to keep the auto import secret, add `managedcluster-import-controller.open-cluster-management.io/keeping-auto-import-secret` to the secret. You can add it by running the following command:

**Comment by cadawson** [comment]
Thanks for picking this up, @swopebe . Added a suggestion for the text. Otherwise, it looks good to me!

**Comment by swopebe** [comment]
@cadawson can you look again?

**Review by cadawson — APPROVED** [review]
Works for me! Thanks a lot!

**Pull request merged**
