### PR TITLE
mgmt13374 add Nutanix

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by berenss** [comment]
Please ask CIM/infra operator engineering for a review of topic 1.5.3.2 to see if Nutanix should be added
[1.5.3.2. Enabling the Central Infrastructure Management service](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/clusters/index#enable-cim)

**Comment by berenss** [comment]
Please ask CIM/infra operator engineering for a review of topic 1.5.7.2 to see if Nutanix should be added
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/clusters/index#scale-hosts-infrastructure-env

**Comment by cadawson** [comment]
Hi @filanov. I have a feeling the answer to the first question is "yes", but less sure about the second one. Can you help? Thanks!

**Comment by filanov** [comment]
As far as i know nutanix UI is not ready for 2.8, but it's possible to use the api

**Comment by dockerymick** [comment]
@cadawson friendly poke. It seems like this PR should be closed. Are these changes still applicable? Is there an issue to add this info? If this change is still needed, I would assume that 2.9 must also be updated

**Comment by cadawson** [comment]
Creating a new PR with new content that was added.

**Pull request closed without merging**
