### PR TITLE
https://issues.redhat.com/browse/ACM-8627- new entry

### PR DESCRIPTION
**Pull request by swopebe**
…some review from support

### CODE REVIEW

**Comment by swopebe** [comment]
@chadcrum sorry for the delay on this. I have added a known issue, but I am not sure I understand the content to explain it well, so please review. I had to edit for our tech writing standards. We can chat to make it better if you think that will help. It is entered a known issue.

**Comment by chadcrum** [comment]
> @chadcrum sorry for the delay on this. I have added a known issue, but I am not sure I understand the content to explain it well, so please review. I had to edit for our tech writing standards. We can chat to make it better if you think that will help. It is entered a known issue.

The write up makes sense to me.

**Review by oafischer — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
