### PR TITLE
Starting on troubleshoot topics gov. for 2.8

### PR DESCRIPTION
**Pull request by dockerymick**
https://issues.redhat.com/browse/ACM-3389

### CODE REVIEW

**Comment by dockerymick** [comment]
@JustinKuli can you also help review this PR since you provided the solution in an [earlier slack thread](https://redhat-internal.slack.com/archives/CU4QXLPQB/p1676317339483169)

**Review by davidtluong — APPROVED** [review]

**Review by oafischer — APPROVED** [review]
Looks great!

**Review by rspagnola — APPROVED** [review]

**Review by JustinKuli — COMMENTED** [review]
I had forgotten about this slack thread so it wasn't obvious to me what we added to make it work. The slack thread gave me extra content on what we had before (which wasn't working)... the thing we added was the `autoindent`.

Can we specify that adding `autoindent` can help? Just to make it more obvious.

**Comment by dockerymick** [comment]
@JustinKuli thanks for your feedback Justin! I just made an update. let me know if that works for you

**Review by JustinKuli — APPROVED** [review]
LGTM!

**Comment by dockerymick** [comment]
@JustinKuli @oafischer @rh-dluong @rspagnola Thanks everyone for the reviews and approvals! Merging this PR

**Pull request merged**
