### PR TITLE
updating the subscription description in RBAC

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/open-cluster-management/backlog/issues/10059

### CODE REVIEW

**Review by ckandag — COMMENTED** [review]
@dockerymick : Not necessarily terrible to add it here.  but this table is for roles and their role, to add this note seems out of place.

Note the same exact information is already documented under the Application LifeCycle section at line #169.  

May be you could link to the App LC section from under the subscription role

**Comment by dockerymick** [comment]
@ckandag thanks for your feedback! Yes, I brought the same concern to Derek. I like your idea of linking to the section for the reader to view more details

**Review by drkho — CHANGES_REQUESTED** [review]
I still like to add a reference here...a link to the section below is ok.

Please note that the problem is an reference of `admin` in the name of **_open-cluster-management:subscription-admin_** here. It implies "admin" capability and can mislead users about the role's permissions to associated resources. Therefore, we need to explicitly state the requirement of access to other resources in other namespaces.

**Comment by dockerymick** [comment]
@drkho to avoid being repetitive, would it be accurate to state the following on Line 169:

To perform application lifecycle tasks, users with the `admin` role must have access to the `application` namespace where the application is created, and to the `managed cluster` namespace.

**Review by drkho — APPROVED** [review]

**Pull request merged**
