### PR TITLE
update credentials and create cluster doc

### PR DESCRIPTION
**Pull request by haoqing0110**
Ref: https://github.com/stolostron/backlog/issues/27049
Signed-off-by: haoqing0110 <qhao@redhat.com>

### CODE REVIEW

**Review by swopebe — APPROVED** [review]

**Comment by cadawson** [comment]
Link to: stolostron/backlog#27049

**Comment by swopebe** [comment]
are you trying to link an additional issue @cadawson? this was already linked: https://github.com/stolostron/rhacm-docs/pull/4460#issue-1500017710

**Pull request merged**
