### PR TITLE
Improving steps for custom Grafana boards

### PR DESCRIPTION
**Pull request by dockerymick**
https://issues.redhat.com/browse/ACM-3052

Included @berenss since he authored the issue, and pulled in @dislbenn since he provided the explanation in Slack. Thanks for yall's help!

### CODE REVIEW

**Review by berenss — APPROVED** [review]
🚀

**Review by dislbenn — APPROVED** [review]
@dockerymick looks good to me!

**Comment by dockerymick** [comment]
@berenss @dislbenn Thanks so much yall!

**Review by oafischer — APPROVED** [review]

**Comment by dockerymick** [comment]
Thanks for your review @oafischer !

**Pull request merged**
