### PR TITLE
[ACM-5636]: Update to L2 file and command info in HyperShift bare metal docs

### PR DESCRIPTION
**Pull request by lahinson**
Continuing work from #5108

### CODE REVIEW

**Comment by lahinson** [comment]
Hi @swopebe @ikke-t - This PR is a continuation from #5108. When you can, PTAL at the new changes and let me know what you think. Thank you both!

**Comment by ikke-t** [comment]
Now that I read the whole doc again, I see the addition is already partly there. See the previous step has:

```
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-public-ip
  namespace: metallb
EOF
```

We actually need to add only some lines to that L2Advertisement section so it becomes like:

```
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-public-ip
  namespace: metallb
spec:
  ipAddressPools:
    - ingress-public-ip
EOF
```

The Spec part is missing from the original. Then you can remove the paragraphs we added here.

**Comment by lahinson** [comment]
Thanks, @ikke-t! I added the spec part and removed the other paragraphs that we had added last week. Let me know what you think when you can.

**Comment by lahinson** [comment]
Just need a final approval from someone on the docs team, and then this one can be merged.

**Review by swopebe — APPROVED** [review]
Thanks so so much!

**Pull request merged**
