### PR TITLE
add grafana timeout to troubleshooting section.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/open-cluster-management/backlog/issues/12121

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
@dockerymick Please take a look at this, we add this for https://github.com/open-cluster-management/backlog/issues/12121

**Comment by swopebe** [comment]
Thanks for the PR, @morvencao. We normally have a `squad doc` issue opened from the issue template, did you have one that you are working with a writer on? @dockerymick FYI

**Comment by morvencao** [comment]
thanks for the kind reminder, I filed a new document task for this: https://github.com/open-cluster-management/backlog/issues/13916

FYI: @dockerymick

**Comment by dockerymick** [comment]
@swopebe @morvencao thank you both! I will review this asap

**Comment by swopebe** [comment]
Sure thing @morvencao -- small changes in a PR are great, larger changes sometimes get lost in PRs if we are looking at our ZenHub board and we don't have the issue. All is well!

**Review by dockerymick — APPROVED** [review]
@morvencao Awesome job with creating the files and making updates! I made a few, very minor changes to the troubleshoot topic. otherwise this looks good to me!

**Pull request merged**
