### PR TITLE
Fix apiVersion in MultiClusterEngine examples

### PR DESCRIPTION
**Pull request by JakobGray**
Signed-off-by: Jakob Gray <20209054+JakobGray@users.noreply.github.com>

### CODE REVIEW

**Review by oafischer — APPROVED** [review]
Looks good, thanks!

**Comment by JakobGray** [comment]
@oafischer Looks like you need to be added to https://github.com/stolostron/rhacm-docs/blob/2.6_stage/OWNERS

**Comment by oafischer** [comment]
I guess 2.3, 2.4, and 2.5 as well given that I've done work for those too. I'll let @cadawson know when I see him again next week. Thanks for pointing that out @JakobGray.

**Comment by cadawson** [comment]
I added oafischer to the owners list that you linked to, but I can't find a place to change another access. You have admin role, but I am not sure if or where we need to change to the owner role. Thoughts? @oafischer @JakobGray . Thanks!

**Comment by JakobGray** [comment]
@cadawson Being in the owners file should let openshift-ci know oafischer can approve PRs. Additionally he can be given getting authority in this repo in the setting tab. Currently oafischer is in the "id" GH team but not the id-admin team: https://github.com/orgs/stolostron/teams/id-admin/members

**Comment by cadawson** [comment]
Thanks for the clarification @JakobGray . I don't think that is something that I can change, based on what I see of my permissions in the list. Someone will be able to respond to Oliver's request.

**Comment by JakobGray** [comment]
@oafischer Can you re-review now that you potentially have approval authority?

**Review by berenss — APPROVED** [review]
wonderful thank you Jake!

**Review by oafischer — APPROVED** [review]
Looks good, thanks!

**Review by swopebe — APPROVED** [review]

**Pull request merged**
