### PR TITLE
Adding Subscription diagram

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/stolostron/backlog/issues/19076

### CODE REVIEW

**Review by swopebe — APPROVED** [review]
I approve, but want to make sure dev does as well.

Thank you for taking this on.

**Comment by dockerymick** [comment]
@birsanv when you have an opportunity, may you review this PR. Back in October, Jess Schaefer, Joy, and Ethan worked on updating the diagrams according to Red Hat standards.

**Comment by birsanv** [comment]
@dockerymick I no longer work on the app component so I am not the right person to review this doc
Adding @xiangjingli , he is the lead for the app lifecycle backend

**Comment by xiangjingli** [comment]
Thanks! It looks good.

**Pull request merged**
