### PR TITLE
add retention config doc

### PR DESCRIPTION
**Pull request by songleo**
fix https://github.com/open-cluster-management/backlog/issues/11915
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by songleo** [comment]
seems we need to update our API doc: https://github.com/open-cluster-management/rhacm-docs/blob/2.3_stage/apis/observability.json.adoc#observability-api @clyang82

**Comment by dockerymick** [comment]
@songleo I have a PR here where I am updating the APIs https://github.com/open-cluster-management/rhacm-docs/pull/2012/files#r617888893

**Review by dockerymick — APPROVED** [review]
These changes look to me, thanks @songleo !

**Comment by dockerymick** [comment]
Going to proceed with merging since it was signed-off and approved

**Pull request merged**
