### PR TITLE
https://issues.redhat.com/browse/ACM-7716 readdressing customer issue

### PR DESCRIPTION
**Pull request by dockerymick**
Previous PR: https://github.com/stolostron/rhacm-docs/pull/5973/files
https://issues.redhat.com/browse/ACM-7716

### CODE REVIEW

**Review by douglascamata — APPROVED** [review]
/lgtm

**Comment by douglascamata** [comment]
@dockerymick thank you for this update 🙇

**Comment by dockerymick** [comment]
Thanks for your review and approval! I see that my base brand changed from stage to prod. I will need to open a new PR with the correct base branch. I will make the same changes and merge the new PR. Also making this update for 2.10 and earlier versions

**Comment by dockerymick** [comment]
Closing this PR

**Pull request closed without merging**
