### PR TITLE
Swope get routes (again) Waiting on development 2.7

### PR DESCRIPTION
**Pull request by swopebe**

### CODE REVIEW

**Comment by swopebe** [comment]
@zlayne confirmed known issue is safe to remove.

**Comment by swopebe** [comment]
@subbarao-meduri @dislbenn please look at this PR, as it needs to get into 2.7 and 2.8 and the doc team has to wrap up 2.8 work soon.

**Comment by swopebe** [comment]
I am still waiting as I cannot merge these or change `oc get routes` without knowing more about th eother changes it causes. @dislbenn @subbarao-meduri, please take a look?

**Comment by dislbenn** [comment]
@swopebe for the troubleshooting section, the following changes will need to be made: 

1. Replace `multicloud-console` with `grafana`
2. Replace `open-cluster-management` with `open-cluster-management-observability`

That should cover the changes for this section.

**Pull request merged**
