### PR TITLE
https://issues.redhat.com/browse/ACM-7175 remove self-managed note 28

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
Hi @xiangjingli . This is the 2.8 removal of the note about self-managed that was requested in ACM-7175[https://issues.redhat.com/browse/ACM-7175]. The same change is in 2.9 and 2.7. Please review and approve if it looks ok here. I can just make the same change to the other versions. Thanks!

**Comment by cadawson** [comment]
Hi @chenz4027. It looks like Xiangjing is out of office. Can you take a look? Thanks!

**Review by chenz4027 — APPROVED** [review]
/lgtm

Confirmed the removal of the note.

**Comment by cadawson** [comment]
Thanks much @chenz4027!

**Pull request merged**
