### PR TITLE
volysync version change

### PR DESCRIPTION
**Pull request by jc-berger**
see jira: https://issues.redhat.com/browse/ACM-10400

### CODE REVIEW

**Comment by jc-berger** [comment]
@tesshuflower would we be able to say now,  "versions 2.10 or later" , like I did in this PR? 

Thanks for taking a look!

**Review by tesshuflower — APPROVED** [review]
/lgtm

**Review by swopebe — COMMENTED** [review]
@jc-berger the issue here is "and later"

**Comment by swopebe** [comment]
This was not peer reviewed so I will reach out in issue. @jc-berger please see comment.

**Pull request merged**
