### PR TITLE
Updating RBAC managedcluster

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/open-cluster-management/backlog/issues/10365

### CODE REVIEW

**Comment by fxiang1** [comment]
@dockerymick Maybe we can add these samples for Application Lifecycle:

To create and administer applications on all managed clusters with a user named username:
- Create a cluster role binding to the cluster role open-cluster-management:cluster-manager-admin and bind it to username by entering the following command:
`oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:cluster-manager-admin --user=<username>`

This role is a super user, which has access to all resources and actions. This role allows you to create the namespace for the application and all application resources in the namespace.

(Optional) To create applications that deploy resources to multiple namespaces, create a cluster role binding to the cluster role open-cluster-management:subscription-admin
and bind it to username by entering the following command:
`oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>`

To create and administer an application named application-name in a managed cluster named cluster-name with a user named username:
- Create a cluster role binding to the cluster role open-cluster-management:admin:<cluster-name> and bind it to username by entering the following command:
`oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:admin:<cluster-name> --user=<username>`

This role will provide read and write access to all application resources on the maneged cluster cluster-name. Repeat this if access for other managed clusters is required.

- Create a namespace role binding to the application namespace using the admin role and bind it to username by entering the following command:
`oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=admin --user=<username>`

This role will provide read and write access to all application resources in the application namspace. Repeat this if access for other applications is required or if the application deploys to multiple namespaces.

- Create a namespace role binding to the channel namespace using the admin role and bind it to username by entering the following command:
`oc create rolebinding <role-binding-name> -n <channel-namespace> --clusterrole=admin --user=<username>`

This role will provide read and write access to all application resources in the channel namspace. Repeat this if access for other channels is required.

(Optional) To create applications that deploy resources to multiple namespaces, create a cluster role binding to the cluster role open-cluster-management:subscription-admin
and bind it to username by entering the following command:
`oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:subscription-admin --user=<username>`

To view an application on a managed cluster named cluster-name with a user named username:
- Create a cluster role binding to the cluster role open-cluster-management:view:<cluster-name> and bind it to username by entering the following command:
`oc create clusterrolebinding <role-binding-name> --clusterrole=open-cluster-management:view:<cluster-name> --user=<username>`

This role will provide read access to all application resources on the maneged cluster cluster-name. Repeat this if access for other managed clusters is required.

- Create a namespace role binding to the application namespace using the view role and bind it to username by entering the following command:
`oc create rolebinding <role-binding-name> -n <application-namespace> --clusterrole=view --user=<username>`

This role will provide read access to all application resources in the application namspace. Repeat this if access for other applications is required.

**Comment by ckandag** [comment]
Hi Mikela,

 I reviewed the the PR and here are some responses to the queries in slack.

_Are there recommended roles that should be used within GRC for ACM?_

**When working with Policies, they are setup in different namespaces.   The rbac is primarily scoped to the namespaces that the policies are setup in.**
**So namespace scoped  ocp-roles admin,edit,view  are what. the user would use for policies.**

**I think the rbac documentation does indicate in the GRC RBAC section ( in the examples , in the console UI table etc).
But it helps we can add the above to make more clear.**

_Which roles have access to secrets (credentials and provider connections)?_

**The provider connections is actually  in CLC team,  while  I believe I know what  RBAC settings are  used there,  probably best to get this info CLC, they will have the latest.**

_Can Kubernetes roles in GRC see secrets in ACM namespace?_

Is this question for the Hub ?   If so,
**As mentioned above roles used for GRC for namespace-scoped admin,edit, view ocp-roles on the policy namespaces.
Among these ocp-role admin and edit have full CRUD access to k8s Secret resources**

**Comment by dockerymick** [comment]
@fxiang1 @ckandag thank you both for your input and feedback. Chaitanya, can you review my changes to the governance lifecycle section ?

**Comment by dockerymick** [comment]
@drkho Derek, may you please provide some input or feedback for the RBAC doc?

**Comment by dockerymick** [comment]
Merging this PR so that I can provide a "stage" version of the docs and prepare to receive feedback from QE

**Pull request merged**
