### PR TITLE
acm5401 upd link to clusterimageset 2.8/2.3

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
Hi @ldpliu. Will you review this fix for the upcoming MCE 2.3? The same information is backported to MCE 2.2, so you don't need to review both if the information is the same. If you would like to take a look, it is at: https://github.com/stolostron/rhacm-docs/pull/5095. Thank you!

**Comment by ldpliu** [comment]
@cadawson I think it should be `backplane-2.3` instead of `backplane-2.2` in 2.8 branch.

**Comment by cadawson** [comment]
@ldpliu: Should I wait for all of the reviewers, or was it for informational purposes?

**Review by dockerymick — APPROVED** [review]
looks good!

**Pull request merged**
