### PR TITLE
open-cluster-management/backlog#11296 ki az actions

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Review by dhrpatel4 — CHANGES_REQUESTED** [review]
Hi @cadawson , can you please replace the "Microsoft Azure provider" with public clouds. It will happen on all env that are not on Bare Metal. I have tested it on public cloud. Thanks

**Comment by cadawson** [comment]
Sure @dhrpatel4 . I have made a change that should cover your request. I thought I read in the issue that it only applies to Azure. Thank you!

**Review by dhrpatel4 — APPROVED** [review]
@cadawson looks good. Thanks

**Review by dockerymick — APPROVED** [review]
Looks good to me! Reminds me of the "refresh" gif lol

**Pull request merged**
