### PR TITLE
Clean unused files; Fix GRC links

### PR DESCRIPTION
**Pull request by dhaiducek**
Removes old/unsed files:
- Symlink to `modules/` inside of the `modules/` directory (which causes an infinite recursion since it's a link to itself)

Updates:
- Fixes some old or broken GRC links

ref: https://issues.redhat.com/browse/ACM-11443

### CODE REVIEW

**Comment by dockerymick** [comment]
@dhaiducek will you attach the issue to this PR please

**Comment by dockerymick** [comment]
Can it be a task added to this issue: https://issues.redhat.com/browse/ACM-11433

**Comment by dhaiducek** [comment]
> Can it be a task added to this issue: https://issues.redhat.com/browse/ACM-11433

No, it's not relevant to the `master.html` files. I've created a new task and attached it: https://issues.redhat.com/browse/ACM-11443

**Comment by oafischer** [comment]
Let me run a build with this branch, if it's green I'll approve.

**Comment by oafischer** [comment]
Build is green, approving

**Review by oafischer — APPROVED** [review]

**Comment by dockerymick** [comment]
@oafischer thanks Oliver! I didn't know when could run a build for a specific local branch. Approving this PR

**Review by dockerymick — APPROVED** [review]

**Comment by dockerymick** [comment]
We will only update the links for 2.10

**Pull request merged**
