### PR TITLE
Updated what's new doc with observability slo dashboard

### PR DESCRIPTION
**Pull request by dislbenn**
Issue: https://github.com/open-cluster-management/backlog/issues/14851, https://github.com/open-cluster-management/backlog/issues/14849, and https://github.com/open-cluster-management/backlog/issues/14731.

Signed-off-by: dislbenn <lavontae.bennett@gmail.com>

### CODE REVIEW

**Comment by dislbenn** [comment]
Doc for this issue: https://github.com/open-cluster-management/backlog/issues/15909

**Review by dockerymick — APPROVED** [review]
@dislbenn Thanks for starting this PR, it looks good! I made a couple changes, but had a small concern about service level overview vs service-label overview. 

I'm assuming that it is written without a hyphen according to your changes. Can Service label overview be updated to service-level overview in Grafana?

**Comment by dockerymick** [comment]
Adding link to [doc issue](https://github.com/open-cluster-management/backlog/issues/15909)

**Comment by dislbenn** [comment]
> @dislbenn Thanks for starting this PR, it looks good! I made a couple changes, but had a small concern about service level overview vs service-label overview.
> 
> I'm assuming that it is written without a hyphen according to your changes. Can Service label overview be updated to service-level overview in Grafana?

@dockerymick I believe `service level` and `service-level` can be interchangeable; therefore, it'll be an easy change in Grafana to switch the label to `service-level`.

**Comment by dockerymick** [comment]
@dislbenn Thanks! That change will help with consistency. We can update the doc after the hyphen is added on the Grafana dashboard. Should I create a separate dev issue to make this update? I am going to create a doc issue so that i can be on the look out for this change

**Comment by dislbenn** [comment]
@dockerymick I think we can create a small dev issue to track the change made. I can also link the PR with the changes to that issue and this doc issue.

**Comment by dislbenn** [comment]
@dockerymick Everything looks good to me, thanks for the review!

**Comment by dislbenn** [comment]
New issue to track dashboard changes: https://github.com/open-cluster-management/backlog/issues/16212.

**Comment by dockerymick** [comment]
@dislbenn confirmed that the changes were made in the Grafana dashboard [here](https://github.com/open-cluster-management/multicluster-observability-operator/pull/762/files), continuing to merge this PR

**Pull request merged**
