### PR TITLE
removing known issues

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-816755862
[Confirmation from Gus](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817832146)

### CODE REVIEW

**Comment by dockerymick** [comment]
Removed the topic, [Console might report cluster policy framework](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817061038), with [confirmation from Yu](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817128349)

**Comment by dockerymick** [comment]
Removed the topic, [Observability add-on stuck in terminating](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817425274), with [confirmation from Marco](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817470523)

**Comment by dockerymick** [comment]
Removed the topic, [Application topology displays incorrect Ansible job status](https://github.com/open-cluster-management/backlog/issues/11209#issuecomment-817835381)

**Review by cadawson — CHANGES_REQUESTED** [review]
This looks good. There is one that said to verify with cluster lifecycle. I know they are looking at them now, so I would like to hold this until they confirm "Console might report managed cluster policy..."

**Comment by cadawson** [comment]
Confirmed with the clc team that the issue can be removed.

**Review by cadawson — APPROVED** [review]
Confirmation done. This looks good for now, and can be merged. Thank you!

**Comment by cadawson** [comment]
Confirmed merge with MJ.

**Comment by dockerymick** [comment]
Thanks for the merge @cadawson !

**Pull request merged**
