### PR TITLE
Update ARO deployment documentation for Subm in 2.7

### PR DESCRIPTION
**Pull request by yboaron**
No need to label GW node manually.

Signed-off-by: Yossi Boaron <yboaron@redhat.com>

### CODE REVIEW

**Comment by MaxBab** [comment]
Thanks @yboaron 

LGTM (QE).

**Review by oafischer — APPROVED** [review]
Looks good, thanks for the update!

**Comment by nyechiel** [comment]
@oafischer this one can be merged :)

**Pull request merged**
