### PR TITLE
ACM-10088: update support for hcp and replace hypershift text

### PR DESCRIPTION
**Pull request by dtthuynh**
https://issues.redhat.com/browse/ACM-10088
- use hcp and hosted cluster language instead of hypershift
- update support level

### CODE REVIEW

**Review by xenolinux — COMMENTED** [review]
LGTM from the docs perspective

**Comment by dtthuynh** [comment]
@rokej can you help review?
@xenolinux if its good can you help approve/merge?

**Review by rokej — APPROVED** [review]
@dtthuynh Looks good to me. Thanks for correcting these.

**Review by xenolinux — APPROVED** [review]

**Pull request merged**
