### PR TITLE
Fix build issues resulting from heading levels

### PR DESCRIPTION
**Pull request by dhaiducek**
Followup to:
- https://github.com/stolostron/rhacm-docs/pull/6753

### CODE REVIEW

**Review by oafischer — APPROVED** [review]
Thanks for fixing this! The entire hosted folder should be extracted soon anyway, but I'm sure the OCP team will appreciate receiving working code. :)

**Comment by swopebe** [comment]
@lahinson FYI.

**Comment by dhaiducek** [comment]
@oafischer I noticed this PR still open, so I wasn't sure if I should hit the button. Is this good to merge?

**Comment by oafischer** [comment]
Looks like Laura left a thumbs up so feel free to merge @dhaiducek, thanks!

**Pull request merged**
