### PR TITLE
https://issues.redhat.com/browse/ACM-4815 Update credentials CA

### PR DESCRIPTION
**Pull request by oafischer**
While working on this I noticed that the console has changed a decent amount since these docs were written. Some steps are in the wrong order and most are not necessary anymore in my opinion since the console is clear enough. Might be another tech debt issue to go through all credentials and update the console steps.

### CODE REVIEW

**Review by dockerymick — CHANGES_REQUESTED** [review]
Will you also add an additional resources section so that you can add inline links at the end? As a reminder or consideration an inline link might be needed in the Prereqs

**Comment by oafischer** [comment]
Excellent reminder, I can convert the inline links, but that means we need to commit to rewriting the credentials docs because it might be a bit weird to have only one topic be written according to our new standards while the others remain untouched.

**Comment by dockerymick** [comment]
@oafischer good point, seems like tech debt to improve the credentials doc. Approving the PR

**Review by dockerymick — APPROVED** [review]
Links were checked as well . thanks for updating this

**Comment by oafischer** [comment]
Thanks for approving @dockerymick, gonna merge so we can address the reported issue for now. I've already talked a bit with Scott to lay out a plan for rewriting credentials. I will create a tech debt issue for this soon.

**Pull request merged**
