### PR TITLE
Fixing troubleshoot book

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/stolostron/backlog/issues/26796
https://github.com/stolostron/rhacm-docs/pull/4448

### CODE REVIEW

**Comment by dockerymick** [comment]
Screen Shot 2023-01-11 at 7 04 59 PM

**Review by oafischer — APPROVED** [review]
Thanks for appeasing the Linter!

**Comment by dockerymick** [comment]
@oafischer lol this is for Pantheon

**Pull request merged**
