### PR TITLE
Removing Custom policy controller doc

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/stolostron/backlog/issues/24296

### CODE REVIEW

**Review by cadawson — APPROVED** [review]
Looks good! If there is some information about what they should access after the removal, please add that. If not, you are all set. Thanks!

**Review by acm-grc-security — APPROVED** [review]
Thanks for taking care of this!

**Comment by dockerymick** [comment]
I am not familiar with the bot. Merging this PR based on @gparvin comment: https://github.com/stolostron/backlog/issues/24296#issuecomment-1209414609

**Comment by dhaiducek** [comment]
I think @gparvin accidentally used our bot account to approve this PR.

**Comment by gparvin** [comment]
Yes. Forgot to logout after I setup a GitHub login on a cluster I created

**Pull request merged**
