### PR TITLE
correct the cluster pool doc

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: Wei Liu <liuweixa@redhat.com>

1. remove the unnecessary description for clsuterset permissions
2. ~~correct the view action for claimed clusters~~

### CODE REVIEW

**Comment by skeeey** [comment]
refer to https://github.com/stolostron/backlog/issues/27039

**Review by swopebe — APPROVED** [review]
peer review

**Comment by skeeey** [comment]
refer to https://github.com/stolostron/backlog/issues/27051

**Review by cadawson — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
