### PR TITLE
Swope errata211

### PR DESCRIPTION
**Pull request by swopebe**
@juliana-hsu at first glance, this is all I saw.... i am waiting on feedback from the Search line (commented in the issue)

### CODE REVIEW

**Review by dockerymick — APPROVED** [review]
Looks good Brandi! Thanks !

**Review by juliana-hsu — COMMENTED** [review]
As you already mentioned we need Jorge / Sherin to comment on the wording for 11904.  Did you document that OCP 4.5 was no longer supported with ACM 2.0.11?  It would be similar wording that went into the 2.1 release.  The user has to upgrade OCP to 4.6 in order to upgrade to ACM 2.0.11.

**Review by juliana-hsu — COMMENTED** [review]
Here's the OCP 4.5 deprecation info:  Starting with ACM 2.0.11, please update the release notes to let customers know that OCP 4.5 is no longer supported. Customers will still be able to use ACM 2.0.10 with OCP 4.5 without interruption, but they will need to upgrade to OCP 4.6 in order to upgrade ACM to 2.0.11.

**Comment by swopebe** [comment]
Yes, @juliana-hsu you should see the OCP statement in there. I documented the ones labeled errata; for the known issue, we it was decided that this close to the Errata, we don't need a known issue bc the fix is coming so soon.

**Comment by juliana-hsu** [comment]
The OCP upgrade statement in the errata isn't correct.  Please have a look at my comment above.

**Comment by juliana-hsu** [comment]
Also, I'll wait on Jorge / Sherin's comments on 11904 before approving.

**Comment by cadawson** [comment]
The versions need to be updated in the support note. I think it should be:

*Important:* You must run {ocp} version 4.6, to upgrade to {product-title-short} version 2.0.11. If you cannot upgrade your {ocp} version to version 4.6, you can continue to use {product-title-short} version 2.0.10.

Version 4.5 is no longer supported. In addition, 4.7 is not supported for 2.0.x. For those reasons, we have to specify 4.6. Other than that, it looks great to me. Thank you!

**Comment by swopebe** [comment]
@cadawson I have made that change already, pinged it to Juliana. Additionally, the translation may not need to be mentioned, but with the label I added it, so also pinged about that. Will merge and refresh when I hear about those.

**Comment by swopebe** [comment]
Restructured the template a bit with @cadawson: 

*Important:* {ocp} 4.5 is not supported with 2.0.11. You must run {ocp} version 4.6 to upgrade to {product-title-short} version 2.0.11. If you cannot upgrade your {ocp} version to 4.6, you can continue to use {product-title-short} version 2.0.10.

For future use, we will build this note as such.

**Comment by juliana-hsu** [comment]
Changes look good.  Thanks!

**Pull request merged**
