### PR TITLE
[MERGE AFTER 2.12 PUBLISH] [2.11_stage] Add `containerArguments` docs to Gatekeeper

### PR DESCRIPTION
**Pull request by dhaiducek**
* Add `containerArguments` docs to Gatekeeper

ref: https://issues.redhat.com/browse/ACM-14700

Cherry-pick:
- #7011

### CODE REVIEW

**Comment by dhaiducek** [comment]
@jc-berger @dockerymick Not sure when 2.11 will be refreshed, but this PR shouldn't merge until Gatekeeper 3.17 is released. If the refresh doesn't happen until next Friday or something, then I think this can merge? Otherwise we should probably wait a bit.

**Comment by dockerymick** [comment]
@dhaiducek will you remind us of the release date for Gatekeeper 3.17. We expect to refresh today

**Comment by dhaiducek** [comment]
Okay, I'll set a reminder for myself to come back around to this. The Gatekeeper 3.17 GA is aligned with ACM 2.12, so I think next Tuesday (assuming it doesn't slip)?

**Comment by dockerymick** [comment]
To help reduce the PRs for pencils down and to avoid merge conflicts, I recommend that we create an issue for this update. After the issue is created and we add this PR to it as a reference, we can close the PR and reopen another after 2.12 GA @dhaiducek

**Comment by dockerymick** [comment]
Here is the link to the new issue: https://issues.redhat.com/browse/ACM-15321
Closing this PR

**Comment by dhaiducek** [comment]
> we can close the PR and reopen another after 2.12 GA @dhaiducek

Since the Gatekeeper files aren't updated much except by us, we ought to be able to re-open this PR when it's ready to be addressed (that ought to be simpler than creating another PR 🙂 )

**Comment by dhaiducek** [comment]
The CI notes a broken link, but it's unrelated to this PR and where the content migrated to is also unclear, so I think this PR should be okay to merge at any time now that Gatekeeper (somewhat unexpectedly) went GA yesterday:

https://github.com/stolostron/rhacm-docs/blob/22ff340768394e6d0dedf0f867d0a288d14155ad/clusters/hosted_control_planes/add_agents_ibmz.adoc?plain=1#L163

**Comment by dockerymick** [comment]
@dhaiducek when i copied and pasted the link it directed me here: https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/#Installing%20RHEL

I think it's fine to leave as is

**Review by dockerymick — COMMENTED** [review]
Approved

**Pull request merged**
