### PR TITLE
https://issues.redhat.com/browse/ACM-10772 Doc errata for 2.5.2 4/10/24

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
Issue: https://issues.redhat.com/browse/ACM-10772
Advisory: https://errata.devel.redhat.com/advisory/129388

**Comment by cadawson** [comment]
Sending a second notice: @rhaignere . Thanks!

**Review by rhaignere — APPROVED** [review]
LGTM, thank you!

**Review by oafischer — APPROVED** [review]
lgtm

**Comment by dockerymick** [comment]
Received approvals and 2.5.2 Advisory is released. It was announced in the channel

**Pull request merged**
