### PR TITLE
bz2027595 update API version

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
Hello @qiujian16 . Here is an update and PR to resolve: https://bugzilla.redhat.com/show_bug.cgi?id=2027595. If it looks ok, we should be done with this one. Thank you!

**Comment by zhiweiyin318** [comment]
@cadawson  this file should be updated too  https://github.com/open-cluster-management/rhacm-docs/blob/2.4_stage/clusters/imp_clust_custom_image_override.adoc

related github issue: https://github.com/open-cluster-management/backlog/issues/18193

**Comment by cadawson** [comment]
Thank you @elgnay !

**Pull request merged**
