### PR TITLE
[ACM-4937]: Update AWS OIDC S3 docs for hosted control planes

### PR DESCRIPTION
**Pull request by lahinson**
Related Jira: https://issues.redhat.com/browse/ACM-4937

This PR makes an update to the OIDC S3 docs to align with recent changes from AWS. This update will be backported to 2.7 and 2.6.

### CODE REVIEW

**Comment by lahinson** [comment]
Received LGTM from engineering (Seth Jennings) on Slack.

**Review by dockerymick — APPROVED** [review]
Looks good, thanks Laura !

**Comment by lahinson** [comment]
Thanks, @dockerymick!

**Pull request merged**
