### PR TITLE
ACM-1952 add user to clstrrolebinding 2.7

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by zhiweiyin318** [comment]
@elgnay  could help take a look at this? I don't know the background about this rolebinding.
cc @ldpliu

**Comment by ldpliu** [comment]
@cadawson I think all `oc create rolebinding/clusterrolebinding` in this section should add the `--user=<username>` flag. 
https://github.com/stolostron/rhacm-docs/blob/2.6_stage/access_control/rbac.adoc#cluster-lifecycle-rbac

**Comment by cadawson** [comment]
Hi @ldpliu. I added the username for both the 2.7 and 2.6 releases. Please take a look, when you have a chance. Thanks!

**Review by swopebe — APPROVED** [review]
peer reviewed

**Review by ldpliu — APPROVED** [review]

**Pull request merged**
