### PR TITLE
Updates for BZ 2081417

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/stolostron/backlog/issues/22190

### CODE REVIEW

**Comment by dockerymick** [comment]
Merging this after i receive approval for this [PR](https://github.com/stolostron/rhacm-docs/pull/3700)

**Review by cadawson — CHANGES_REQUESTED** [review]
Thanks Mikela. I added a few minor cosmetic changes, for the most part. I think this change is ok, as the other examples of names that I find are lowercase and dashes. I suggest that you run it by Chris Doan, if you haven't checked with anyone yet, as I believe he is familiar with ImageContentSourcePolicy.

**Comment by dockerymick** [comment]
@cadawson Thanks for your review and commits Chris! I didn't want to override the progress you all were making with the cluster doc. I agree with these changes and have reached out to @cdoan1

**Comment by cdoan1** [comment]
This is the closest example I could find; [https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5[…]ngle/preparing_to_deploy_in_a_disconnected_environment/index](https://access.redhat.com/documentation/en-us/red_hat_openshift_container_storage/4.5/html-single/preparing_to_deploy_in_a_disconnected_environment/index#creating-operator-imagecontentsourcepolicy_rhocs)
They use <your-registry>  for the mirrors section. I’ll change it from <your-local-mirror> to <your-local-mirror-name> and change <path-to-local-mirror> to <your-registry>
Thoughts?

cdoan: 
ok, as long as we have precidence , we're good to go

**Review by cdoan1 — APPROVED** [review]
ok, as long as we have precidence , we're good to go

**Comment by dockerymick** [comment]
Adding screen captures of the convo and confirmation

Screen Shot 2022-07-14 at 10 25 19 AM
Screen Shot 2022-07-14 at 10 25 30 AM
Screen Shot 2022-07-14 at 10 27 10 AM

**Comment by dockerymick** [comment]
I also received confirmation from @cadawson that he is fine with me merging this PR. Merging

**Pull request merged**
