### PR TITLE
https://issues.redhat.com/browse/ACM-5166 correcting navigation steps and removing yaml references

### PR DESCRIPTION
**Pull request by faaden123**
Followed the issue information provided on issue 5166. There was a navigation error and an issue with YAML being mentioned, but there being no YAML in informational steps. I took those out seeing as the assumption was that they aren't needed and corrected the navigation.

### CODE REVIEW

**Comment by chenz4027** [comment]
@faaden123 Just wondering, I'm not seeing the removal of YAMLs, are they taken care by a separate PR?

**Comment by faaden123** [comment]
> @faaden123 Just wondering, I'm not seeing the removal of YAMLs, are they taken care by a separate PR?

Oh no they should be in there. let me take a look.

**Comment by faaden123** [comment]
> @faaden123 Just wondering, I'm not seeing the removal of YAMLs, are they taken care by a separate PR?

@chenz4027 they should be on there now!

**Review by chenz4027 — APPROVED** [review]
/lgtm
Thanks!

**Review by dockerymick — APPROVED** [review]
Changes look good to me !

**Pull request merged**
