### PR TITLE
https://issues.redhat.com/browse/ACM-5430 and ACM-6737 Add CLI instru…

### PR DESCRIPTION
**Pull request by cadawson**
…ctions for creating cluster on premises and Nutanix 2.7

### CODE REVIEW

**Comment by cadawson** [comment]
This is a back-port from https://github.com/stolostron/rhacm-docs/pull/5153 and https://github.com/stolostron/rhacm-docs/pull/5512. Should be ready to go, but would like final confirmation.

**Comment by cadawson** [comment]
We merged this into 2.8 along with the Nutanix instructions. Lookin to backport it here into 2.7. I just want to confirm that the procedure is the same. Thanks @filanov @avishayt @chadcrum!

**Comment by cadawson** [comment]
Nutanix was not supported in 2.7, so removing those changes from this backport.

**Comment by filanov** [comment]
As you said there is no nutanix support in 2.7 but there is `VSphere` so it worth mentioning that. 
Besides that LGTM

**Comment by cadawson** [comment]
This is a backport to 2.7.

**Pull request merged**
