### PR TITLE
https://issues.redhat.com/browse/ACM-15852 for 2.13

### PR DESCRIPTION
**Pull request by dockerymick**
Removed the row about policy compliance history API since it will be removed for 2.13: https://issues.redhat.com/browse/ACM-15644

### CODE REVIEW

**Review by showeimer — APPROVED** [review]
Thank you!

**Comment by dockerymick** [comment]
@showeimer Thanks for the quick review and approval! After I receive a peer review, i'll update 2.12

**Review by jc-berger — APPROVED** [review]
/lgtm

**Comment by dockerymick** [comment]
@showeimer @jc-berger thanks to you both for your reviews and approvals!

**Pull request merged**
