### PR TITLE
[ACM-4937]: Another update to the AWS S3 bucket instructions

### PR DESCRIPTION
**Pull request by lahinson**
Related Jira: https://issues.redhat.com/browse/ACM-4937

Related PR: #4934

From Seth Jennings on Slack: This PR adds another section of code that the user needs to add during bucket creation.

### CODE REVIEW

**Comment by lahinson** [comment]
Waiting for the development PR to be merged before requesting peer review.

**Review by swopebe — APPROVED** [review]
Thanks for pulling us in!

**Pull request merged**
