### PR TITLE
update resource request doc

### PR DESCRIPTION
**Pull request by songleo**
we add some new components for observability service. so we need to update the resource request doc. more resource request details refer to: https://docs.google.com/spreadsheets/d/15nG2hc-wBJgPn1qvQZy3HPBwy8YamJT4ZQkwvpFUiz0/edit#gid=1542855038

https://github.com/open-cluster-management/backlog/issues/13740
Signed-off-by: Song Song Li <ssli@redhat.com>

### CODE REVIEW

**Comment by songleo** [comment]
@dockerymick do you know how to merge the table like this via markdown, thanks

image

**Comment by dockerymick** [comment]
@songleo Thanks for opening this! im not sure how to in .adoc, but I have the manual and can figure it out! I will more likely start on the review for this later in the week.

**Review by dockerymick — APPROVED** [review]
I have made updates for the table. I will approve this and await for Song Song's review in case there is another update that should be made in this file

**Pull request merged**
