### PR TITLE
Updating the apiVersion for policy set

### PR DESCRIPTION
**Pull request by dockerymick**
https://github.com/stolostron/backlog/issues/23138

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]
LGTM! Thanks, @dockerymick!

**Review by dhaiducek — CHANGES_REQUESTED** [review]
Actually, looks like there's one more instance at the bottom of the page.

**Comment by oafischer** [comment]
Like @dhaiducek said there is one more instance further down the file. Otherwise looks good!

**Comment by dockerymick** [comment]
@oafischer @dhaiducek Thanks! recently updated

**Review by swopebe — APPROVED** [review]

**Review by dhaiducek — APPROVED** [review]

**Comment by dockerymick** [comment]
Thanks for your review ! @swopebe @dhaiducek

**Pull request merged**
