### PR TITLE
https://issues.redhat.com/browse/ACM-7716 mountVolumes observability

### PR DESCRIPTION
**Pull request by dockerymick**
https://issues.redhat.com/browse/ACM-7716

### CODE REVIEW

**Review by douglascamata — APPROVED** [review]
/lgtm

**Comment by dockerymick** [comment]
@douglascamata thanks for your review and approval! Reaching out to my team to receive a peer review.

**Review by oafischer — APPROVED** [review]
Looks great, thanks!

**Comment by dockerymick** [comment]
@oafischer thanks for your review and approval!

**Pull request merged**
