### PR TITLE
Add label selector to `lookup` template documentation

### PR DESCRIPTION
**Pull request by dhaiducek**
Dev task ref: https://issues.redhat.com/browse/ACM-5032
Doc task ref: https://issues.redhat.com/browse/ACM-5286

### CODE REVIEW

**Review by dockerymick — APPROVED** [review]
Made an update from docs perspective

**Comment by dockerymick** [comment]
After another developer approves, we are good to merge this

**Review by gparvin — APPROVED** [review]
Thanks, looks good to me.

**Comment by dockerymick** [comment]
@gparvin thanks for your approval. Merging this

**Pull request merged**
