### PR TITLE
https://github.com/stolostron/backlog/issues/26607, 2.7 remove (peer/tech edit)

### PR DESCRIPTION
**Pull request by swopebe**
…ased on a 2.6 announcement and alternative from dev team, @cadawson FYI/

### CODE REVIEW

**Review by cadawson — APPROVED** [review]
Looks good. Thanks.

**Comment by cadawson** [comment]
This was confirmed for removal by @qiujian16 in the scrum meeting. It was intended to be a procedure that internal Red Hat teams use, rather than customers.

**Comment by cadawson** [comment]
Hi @qiujian16. Will you please take a look at this change for removing the "Deploying workloads using ManifestWork" topic? We talked about it during the scrum meeting. Is there a different procedure that customers should use for this that we can link to from the removal and deprecations files? Thanks!

**Comment by swopebe** [comment]
In that case, I will remove from 2.7 and simply add it to the removal table for 2.6. But I still need info about other mentions of manifest work. Do we remove all mentions of it? (you can search to see it)

**Pull request merged**
