### PR TITLE
Add broker known issue 2.7 stolostron/backlog#27008

### PR DESCRIPTION
**Pull request by oafischer**
https://github.com/stolostron/backlog/issues/27008

### CODE REVIEW

**Review by cadawson — APPROVED** [review]
Looks good. A couple of quick questions: 
1. Does this always happen, or is it occasional? In the title it sounds like always, but in the text, it says "might". Just provides someone with expectations, if it does or doesn't always happen. 
2. Will they know where to set the InsecureBrokerConnection to true?

**Comment by oafischer** [comment]
It happens sometimes so I'll change the title to reflect that!

Second question might be better suited for @skitt

**Comment by skitt** [comment]
Regarding the second question, perhaps we can add a link to the Submariner customizations section, and add a mention there — the result would be

```
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
   name: submariner
   namespace: <managed-cluster-namespace>
spec:
   insecureBrokerConnection: true
```

**Comment by oafischer** [comment]
Thanks for providing the sample @skitt! I think it's better to keep everything together, so I'll just add that sample to the known issue. Let me know if the changes look good.

**Review by skitt — APPROVED** [review]

**Pull request merged**
