### PR TITLE
Remove outdated Submariner prerequisites

### PR DESCRIPTION
**Pull request by dfarrell07**
Closes stolostron/backlog#23455

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Review by aswinsuryan — APPROVED** [review]

**Review by cadawson — COMMENTED** [review]
Thanks @dfarrell07 . I understand the need to remove the Globalnet note. Is the requirement for 4.6, and later no longer an issue? Maybe this is because versions earlier than 4.6 are no longer supported, but does that mean that people still won't be running an older version and try this? 
Same question for the 4.4 statement. 
If there is no concern about people running and trying to add Submariner to an older version, it is right to remove it. Just wanted to make sure that there might not be someone who tries something unexpected and expects support.

**Comment by dfarrell07** [comment]
Yeah I think the assumption is that people should not be running these older versions by the time they get to the Submariner docs because they have already validated their setup with the support matrix. @nyechiel might have more to say.

**Comment by nyechiel** [comment]
In general, these are very old k8s versions which are not supported by ACM. I don't see any value keeping it here (I believe this was just copied from the upstream docs).

**Review by cadawson — APPROVED** [review]
Looks good. Thanks!

**Comment by cadawson** [comment]
Opened issue #23508 for this.

**Pull request merged**
