### PR TITLE
Add missing step in Subm 2.5

### PR DESCRIPTION
**Pull request by oafischer**
https://github.com/stolostron/backlog/issues/26703

### CODE REVIEW

**Review by cadawson — APPROVED** [review]
Looks good. Thanks!

**Comment by dfarrell07** [comment]
Isn't this step itself step 5?

step5

**Comment by dfarrell07** [comment]
The report makes sense for 2.6, where this point is step 6.

https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.6/html/add-ons/add-ons-overview#deploying-submariner-mcaddon-api

**Comment by oafischer** [comment]
You are right @dfarrell07! Good catch, I should have looked more closely. I'll close this one and try again.

**Pull request closed without merging**
