### PR TITLE
no issue - update links

### PR DESCRIPTION
**Pull request by cadawson**

### CODE REVIEW

**Comment by cadawson** [comment]
HI @filanov . There was a request from Fatih Nar to replace the 4.9 URL examples with 4.10 examples in this file. Is it sufficient to change 4.9 to 4.10, or was there more of a structure change for the 4.10 URLs? Thanks!

**Comment by filanov** [comment]
The link don't work, `File not found` 
try to use one of the links from https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.10/4.10.3/

**Comment by filanov** [comment]
and https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.10/4.10.3/

**Comment by cadawson** [comment]
Thanks @filanov . I've updated the links with the 4.10 versions. Does this look ok?

**Comment by filanov** [comment]
LGTM

**Pull request merged**
